name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
# jobs:
#   deploy:
#     name: Deploy to GitHub Pages
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 14.x
#           cache: yarn
#       - name: Build website
#         working-directory: website
#         run: |
#           yarn install --frozen-lockfile
#           yarn build

#       # Popular action to deploy to GitHub Pages:
#       # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # Build output to publish to the `gh-pages` branch:
#           publish_dir: ./website/build
#           # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
#           # https://github.com/actions/checkout/issues/13#issuecomment-724415212
#           # The GH actions bot is used by default if you didn't specify the two fields.
#           # You can swap them out with your own user credentials.
#           user_name: github-actions[bot]
#           user_email: 41898282+github-actions[bot]@users.noreply.github.com
